services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://adminCineCampus:Cine2024@autorack.proxy.rlwy.net:20722/cineCampus 
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "20722:20722"
    volumes:
      - ./data/db:/data/db